### ISSUE TITLE
Broken links in "Get Cards" Tab

### ISSUE THREAD

**Issue by cancastilho** [OWASP/www-project-cornucopia#6]
I've found some broken links here in [Get Cards Tab](https://github.com/OWASP/www-project-cornucopia/blob/master/tab_cards.md).  Check the "Source Files" section. 

Just reporting so you can fix them.

**Comment by ChristopherHackett** [comment]
Just come here to report the same thing 

Looks like this is caused by a change to the file names been outputted. For each version of the deck there are two files (  `_dynamic` & `_static`) however I don't know enough about which would be the right one to link here to issue a PR to fix this.  

Links affected ...

https://github.com/OWASP/www-project-cornucopia/blob/7cdca4528c4d3f68cf3d48b48897f762ccd517db/tab_cards.md?plain=1#L33-L36

**Comment by rewtd** [comment]
Thank you! I'll get that corrected. Probably best if I kept the "static" cards (the old, default ones) as they are rather than renaming them.

**Comment by rewtd** [comment]
Links corrected. Thank you!
